etcd:
    image: registry.vxcontrol.com:8443/etcd:v3.2.9-1
    labels:
        io.rancher.scheduler.affinity:host_label_soft: etcd=true
        io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
        io.rancher.sidekicks: data
    environment:
        RANCHER_DEBUG: '${RANCHER_DEBUG}'
        EMBEDDED_BACKUPS: '${EMBEDDED_BACKUPS}'
        BACKUP_PERIOD: '${BACKUP_PERIOD}'
        BACKUP_RETENTION: '${BACKUP_RETENTION}'
    volumes:
    - etcd:/pdata
    - ${BACKUP_LOCATION}:/data-backup
    volumes_from:
    - data
    external_links:
    - etcd-lb:loadbalancer
data:
  image: busybox
  command: /bin/true
  net: none
  volumes:
  - /data
  volume_driver: ${STORAGE_DRIVER}
  labels:
    io.rancher.container.start_once: 'true'
etcd-lb:
  expose:
  - 2379:2379/tcp
  tty: true
  image: rancher/load-balancer-service
  links:
  - etcd:etcd
  stdin_open: true